/*
 * PROJECT:   Assassin
 * FILE:      BackgroundWorker.idl
 * PURPOSE:   Definition for the BackgroundWorker
 *
 * LICENSE:   The MIT License
 *
 * DEVELOPER: Mouri_Naruto (Mouri_Naruto AT Outlook.com)
 */

namespace Assassin
{
    runtimeclass BackgroundWorker :
        Windows.ApplicationModel.Background.IBackgroundTask
    {
        BackgroundWorker();
    }
}
