/******************************************************************************
Project: Assassin
Description: Definition for the CustomConverter.
File Name: CustomConverter.idl
License: The MIT License
******************************************************************************/

namespace Assassin
{
    [Windows.UI.Xaml.Data.Bindable]
	[Windows.Foundation.Metadata.WebHostHidden]
	runtimeclass CustomConverter :
        [default] Windows.UI.Xaml.Data.IValueConverter
    {
		CustomConverter();
    }
}
