/******************************************************************************
Project: Assassin
Description: Definition for the TaskListEmptyToVisibilityConverter.
File Name: TaskListEmptyToVisibilityConverter.idl
License: The MIT License
******************************************************************************/

namespace Assassin
{
    [Windows.UI.Xaml.Data.Bindable]
	[Windows.Foundation.Metadata.WebHostHidden]
	runtimeclass TaskListEmptyToVisibilityConverter :
        [default] Windows.UI.Xaml.Data.IValueConverter
    {
		TaskListEmptyToVisibilityConverter();
    }
}
