/******************************************************************************
Project: Assassin
Description: Definition for the TaskStatusToVisibleConverter.
File Name: TaskStatusToVisibleConverter.idl
License: The MIT License
******************************************************************************/

namespace Assassin
{
    [Windows.UI.Xaml.Data.Bindable]
	[Windows.Foundation.Metadata.WebHostHidden]
	runtimeclass TaskStatusToVisibleConverter :
        [default] Windows.UI.Xaml.Data.IValueConverter
    {
		TaskStatusToVisibleConverter();
    }
}
