/******************************************************************************
Project: Assassin
Description: Definition for the Uint64ByteSizeToStringConverter.
File Name: Uint64ByteSizeToStringConverter.idl
License: The MIT License
******************************************************************************/

namespace Assassin
{
    [Windows.UI.Xaml.Data.Bindable]
	[Windows.Foundation.Metadata.WebHostHidden]
	runtimeclass Uint64ByteSizeToStringConverter :
        [default] Windows.UI.Xaml.Data.IValueConverter
    {
		Uint64ByteSizeToStringConverter();
    }
}
