/******************************************************************************
Project: Assassin
Description: Definition for the Uint64RemainTimeToStringConverter.
File Name: Uint64RemainTimeToStringConverter.idl
License: The MIT License
******************************************************************************/

namespace Assassin
{
    [Windows.UI.Xaml.Data.Bindable]
	[Windows.Foundation.Metadata.WebHostHidden]
	runtimeclass Uint64RemainTimeToStringConverter :
        [default] Windows.UI.Xaml.Data.IValueConverter
    {
		Uint64RemainTimeToStringConverter();
    }
}
