/*
 * PROJECT:   Nagisa
 * FILE:      CustomConverter.idl
 * PURPOSE:   Definition for the CustomConverter.
 *
 * LICENSE:   The MIT License
 *
 * DEVELOPER: Mouri_Naruto (Mouri_Naruto AT Outlook.com)
 */

namespace Nagisa
{
    [Windows.UI.Xaml.Data.Bindable]
    [Windows.Foundation.Metadata.WebHostHidden]
    runtimeclass CustomConverter :
        [default] Windows.UI.Xaml.Data.IValueConverter
    {
        CustomConverter();
    }
}
